13 develop compose file
BrandonRS/get5-web pull request #27
Opened 2022-02-21 22:06 UTC by rathoddhruv26

WIP PR dev comp file not done yet, needs to mount container path /data/db to host path ./data  - Dhruv

2022-02-22 07:49 UTC, BrandonRS commented
This is set to merge to master. It should be merged to develop.
Also, you didn't add the docker-compose.develop.yml file to the branch.

2022-02-22 15:11 UTC, rush2sk8 requested changes

2022-02-22 15:11 UTC, rush2sk8 commented on docker-compose.yml
> +      dockerfile: ./Dockerfile
dont need to specify dockerfile if its the only one in the dir

2022-02-22 15:11 UTC, rush2sk8 commented on get5-web/Program.cs
> +app.Run();
pls add newlines at the end of files

2022-02-22 15:11 UTC, rush2sk8 commented on .dockerignore
> +node_modules/
needs a newline

2022-02-22 15:11 UTC, rush2sk8 commented on Dockerfile
> +ENTRYPOINT ["dotnet", "get5-web.dll"]
add newline

2022-02-22 15:11 UTC, rush2sk8 commented on docker-compose.yml
> +      - "8080:80"
keep in mind 8080 is hella overused port so if you end up adding any other services or something make sure to make them on a different port otherwise you can have a collision

2022-02-22 15:11 UTC, rush2sk8 commented on get5-web/Properties/launchSettings.json
> +}
newline

2022-02-22 15:13 UTC, Andylovesmangos commented on get5-web/Properties/launchSettings.json
> +}
go off king

2022-02-22 15:28 UTC, BrandonRS commented on docker-compose.yml
> +      dockerfile: ./Dockerfile
He could have done "build: .", but this is how it was done in old versions, so not a big deal.

2022-02-22 15:29 UTC, BrandonRS commented on get5-web/Program.cs
> +app.Run();
We use CodeMaid in VS, which strips newlines. We aren't in a linux environment as well, so its fine.

2022-02-22 15:30 UTC, BrandonRS commented on docker-compose.yml
> +      - "8080:80"
Actually a good suggestion, I'll add a ticket to change that.

2022-02-22 15:34 UTC, BrandonRS commented on Dockerfile
> +ENTRYPOINT ["dotnet", "get5-web.dll"]
See other comment.

2022-02-22 15:34 UTC, BrandonRS commented on .dockerignore
> +node_modules/
See other comment.

2022-02-22 21:05 UTC, BrandonRS commented on docker-compose.develop.yml
> +    deploy:
Use _restart:_ option instead of _deploy:restart_policy_.

2022-02-22 21:06 UTC, BrandonRS commented on docker-compose.develop.yml
> +    build:
No build for this, we just want the official mongo image.

2022-02-22 21:06 UTC, BrandonRS commented on docker-compose.develop.yml
> +    build:
No build

2022-02-22 21:06 UTC, BrandonRS commented on docker-compose.develop.yml
> +    deploy:
Also, good to do this for mongo-express as well.

2022-02-22 21:07 UTC, BrandonRS commented on docker-compose.develop.yml
> +    image: mongo
Wrong image

2022-02-22 21:08 UTC, BrandonRS requested changes
Address comments. Also, check the _volumes:_ option for compose files for mounting the data directory.

2022-02-24 04:52 UTC, rathoddhruv26 commented on docker-compose.develop.yml
> +    deploy:
I thought restart: option was a version 2x option, and outdated, when I looked at the documentation

2022-02-24 04:53 UTC, rathoddhruv26 commented on docker-compose.develop.yml
> +    build:
got rid of build

2022-02-24 04:54 UTC, rathoddhruv26 commented on docker-compose.develop.yml
> +    image: mongo
changed image to mongo-express

2022-02-24 04:54 UTC, rathoddhruv26 commented on docker-compose.develop.yml
> +    build:
removed build

2022-02-24 05:12 UTC, rathoddhruv26 commented on docker-compose.yml
> +      - "8080:80"
pretty sure I set it to 8081 but I didnt pull the right code or something, thats old and fixed now though.

2022-02-24 05:23 UTC, BrandonRS commented on docker-compose.develop.yml
> +    deploy:
https://github.com/BrandonRS/get5-web/blob/develop/docker-compose.yml#L7

2022-02-28 08:40 UTC, BrandonRS commented on docker-compose.develop.yml
> +  data:
No volume needed.

2022-02-28 08:41 UTC, BrandonRS commented on docker-compose.develop.yml
> +      -data:/data/db
Should be local mount to _data_ folder, not to docker volume.

2022-02-28 15:07 UTC, BrandonRS commented on docker-compose.develop.yml
> +      -./data:/data/db
Space between "-" and ".".

2022-02-28 15:20 UTC, rathoddhruv26 commented on docker-compose.develop.yml
> +      -./data:/data/db
Done

2022-03-01 15:05 UTC, merged